theme = 'tailbliss-main'
baseURL = ""
title = "Crobotics #7201"

languageCode = "en-us"
defaultContentLanguage = 'hr'
defaultContentLanguageInSubdir = true

enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
darkmode_js = ["assets/js/darkmode.js"]
enableInlineShortcodes = true


[languages]
    [languages.en]
        description = "Official Crobotics #7201 website"
        fap = "Fast and productive"
        wassup = "What's new"
        shortDesc = "A small team of high school students aiming to compete at a high level with a tight budget."

        missionTitle = "Our Vision"
ourGoal1 = "We want to show everyone who competes that success does not depend on money and resources, but on passion, effort, and perseverance. We believe that with the right approach and mindset, anyone can achieve their goals, regardless of the conditions they come from. "
ourGoal2 = "Over the years, as a team, we have faced competitors with significantly greater resources, but that has not stopped us from achieving notable results. These experiences have further motivated us to keep improving and to believe in what we do. Our goal is to encourage others to believe in themselves and not give up when faced with challenges, because that is exactly what leads us toward greater success year after year. "

ourJourneyTitle = "Our Journey of Growth and Success"
ourJourney = "The Crobotics team was founded in 2017 at Andrija Mohorovičić High School in Rijeka, on the initiative of student Borna Massari, with the support of Prof. Patricija Nikolaus, Prof. Goran Boneta, and six other students. From the very beginning, the team has continuously developed, bringing together new generations of students and building a community based on knowledge, cooperation, and a passion for robotics. 
Already in 2018, we participated in the FIRST Robotics Competition in New York, where we won two awards: the Rookie Inspiration Award and the Highest Rookie Seed Award. In 2020, we competed in Istanbul and placed 22nd in Europe, and in 2023 we returned to Istanbul, where we achieved an outstanding 5th place, which was our greatest success at the time. 
Our journey continued in 2026 in Chicago, where, by winning 3rd place, we achieved a historic result and set a new standard for our team, once again showing how much effort, perseverance, and teamwork can pay off. "
       
        investorsTitle = "Backed by world-renowned investors"
        investorsText = "Of course, participating in competitions costs a lot of money, from buying materials to registration fees and travel expenses. Since our team is consisted of high school students and two mentors, collecting resources needed for paying everything was a tough job. We couldn't have done anything without our renowned investors: TSI d.o.o, LNG Hrvatska d.o.o., Infobip d.o.o., Faculty of Engineering in Rijeka (RITEH), Primorsko-goranska županija, Grad Rijeka and other."
        investorsLink = "Meet our investors"

        aboutText = "About"
        blogText = "Blog"
        readMoreText = "Read more about our adventures"
        newsText = "News"
        donateText = "Donate"
        contactText = "Contact"
        postsText = "Posts"
        catText = "Categories"

        copyrightText = "All rights reserved."
        plug1 = "This site was developed by"
        plug2 = "using"
        plug3 = "template as the starting ground."

        lang = "Hrvatski"

    [languages.hr]
        description = "Službena stranica Crobotics #7201"
        fap = "Učinkoviti i inovativni"
        wassup = "Novosti"
        shortDesc = "Mali tim srednjoškolaca s ciljem natjecanja na visokoj razini s ograničenim budžetom."

        missionTitle = "Naša vizija"
        ourGoal1 = "Želimo pokazati svima koji se natječu da uspjeh ne ovisi o novcu i resursima, već o strasti, trudu i upornosti. Vjerujemo da uz pravi pristup i način razmišljanja svatko može ostvariti svoje ciljeve, bez obzira na uvjete iz kojih dolazi. "
        ourGoal2 = "Kroz godine smo se kao tim suočavali s konkurencijom koja raspolaže znatno većim resursima, no to nas nije spriječilo da ostvarimo zapažene rezultate. Upravo ta iskustva dodatno su nas motivirala da nastavimo napredovati i vjerovati u ono što radimo. Naš cilj je potaknuti druge da vjeruju u sebe te da ne odustaju pred izazovima jer je upravo to ono što nas iz godine u godinu vodi prema sve većim uspjesima. "

        ourJourneyTitle = "Naš put rasta i uspjeh"
        ourJourney = "Crobotics tim osnovan je 2017. godine u Gimnaziji Andrije Mohorovičića Rijeka na inicijativu učenika Borne Massarija, uz podršku prof. Patricije Nikolaus, prof. Gorana Bonete i još šest učenika. Od samih početaka tim se kontinuirano razvija, okupljajući nove generacije učenika i gradeći zajednicu temeljenu na znanju, suradnji i strasti prema robotici. 
Već 2018. godine sudjelovali smo na FIRST Robotics Competitionu u New Yorku, gdje smo osvojili dvije nagrade: Rookie Inspiration Award i Highest Rookie Seed Award. Godine 2020. natjecali smo se u Istanbulu i zauzeli 22. mjesto u Europi, a 2023. ponovno smo nastupili u Istanbulu gdje smo ostvarili izvanredno 5. mjesto, što je tada bio naš najveći uspjeh. 
Naše putovanje nastavilo se i 2026. godine u Chicagu, gdje smo osvojivši 3. mjesto ostvarili povijesni rezultat te postavili novi standard za naš tim i još jednom pokazali koliko se trud, upornost i timski rad mogu isplatiti. "

        investorsTitle = "Uz podršku svjetski poznatih investitora"
        investorsText = "Naravno, sudjelovanje na natjecanjima košta puno novca, od kupnje materijala do kotizacija i putnih troškova. Budući da naš tim čine srednjoškolci i dva mentora, prikupljanje sredstava potrebnih za plaćanje svega je bio težak posao. Ništa ne bismo mogli bez naših renomiranih investitora: TSI d.o.o, LNG Hrvatska d.o.o., Infobip d.o.o., Tehnički fakultet u Rijeci (RITEH), Primorsko-goranska županija, Grad Rijeka i ostalih."
        investorsLink = "Upoznajte naše donatore"

        aboutText = "O nama"
        
        newsText = "Novosti"
        contactText = "Kontakti"
        postsText = "Objave"
        donateText = "Doniraj"
        catText = "Kategorije"
        blogText = "Blog"
        readMoreText = "Pročitajte više na našem blogu"

        copyrightText = "Sva prava pridržana."
        plug1 = "Ovu stranicu razvio je"
        plug2 = "koristeći"
        plug3 = "predložak kao polaznu osnovu."

        lang = "English"


[params]
author = "Crobotics #7201"
authorimage = "../assets/images/global/crobotics_logo.png"
og_image = "/images/crobotics_logo.png"
sitename = "Crobotics #7201"
description = "Official Crobotics #7201 website"


[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Categories"
tag = "Tags"

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.105.0"
    max = "0.105.0"